dry: false

mode: 'supervised'
model_name: 'segformer'
model_id: 'nvidia/segformer-b0-finetuned-ade-512-512'
checkpoint:

do_normalize: false
contrast_factor: 1
brightness_factor: 1
gamma_factor: 1
hue_factor: 0
sharpness_factor: 1
saturation_factor: 1


tile_size: 512
num_labels: 4
random_state: 42

devices: [ 1 ]
max_epochs: 100
batch_size: 16
num_workers: 23

# criterion: CrossEntropyLoss
val_check_interval: 1.0
early_stopping_patience: 15
reduce_lr_on_plateau_patience: 7
reduce_lr_on_plateau_factor: 0.5
lr: 0.000005
