path:
  data: 'data'
  models: 'models'
  reports: 'reports'
  submissions: 'submissions'
  logs: 'logs'

wandb:
  entity: 'association-rosia'
  project: 'stranger-sections-2'

data:
  mean: [0.4175, 0.3497, 0.2607]
  std: [0.2044, 0.1909, 0.1867]