dry: false

mode: 'semi_supervised'
model_name: 'mask2former'
model_id: 'facebook/mask2former-swin-large-cityscapes-semantic'
checkpoint:

sam_model_id: 'facebook/sam-vit-huge' # 'facebook/sam-vit-base'
sam_input_points_num: 50
sam_input_points_rate_ones: 0.5

do_normalize: false
tile_size: 384
num_labels: 4
random_state: 42

contrast_factor: 1
brightness_factor: 1
gamma_factor: 1
hue_factor: 0
sharpness_factor: 1
saturation_factor: 1

devices: [ 2 ] # [ 0, 1, 2, 3 ]
max_epochs: 100
batch_size: 4
num_workers: 23
val_check_interval: 1.0
early_stopping_patience: 15
reduce_lr_on_plateau_patience: 7
reduce_lr_on_plateau_factor: 0.5
lr: 0.00005

