dry: false

mode: 'semi_supervised'
model_name: 'segformer'
model_id: 'nvidia/segformer-b0-finetuned-ade-512-512'
sam_id: 'facebook/sam-vit-base'
checkpoint:

do_normalize: false
tile_size: 512
contrast_factor:
num_labels: 4
random_state: 42

devices: [ 0, 1, 2, 3 ] # [ 0 ]
max_epochs: 100
batch_size: 4
num_workers: 23
val_check_interval: 1.0
early_stopping_patience: 15
reduce_lr_on_plateau_patience: 7
reduce_lr_on_plateau_factor: 0.5
lr: 0.000005

